// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StaffControlServer.Context;

#nullable disable

namespace StaffControlServer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240612103545_RoleEdited")]
    partial class RoleEdited
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("StaffControlServer.Data.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("1d2351af-e8f1-4974-b776-829d47139bab"),
                            RoleId = new Guid("cedeec66-2594-4a0a-a8b5-d52acfc9fb96")
                        });
                });

            modelBuilder.Entity("StaffControlServer.Data.Calendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("StaffControlServer.Data.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a99f1722-ecf8-45bb-a049-f3c64449f304"),
                            DateCreated = new DateTime(2024, 6, 12, 10, 35, 44, 786, DateTimeKind.Utc).AddTicks(911),
                            Name = "Отдел маркетинга"
                        },
                        new
                        {
                            Id = new Guid("f79f1e85-ced4-4a4b-8f13-9f29bb48a90a"),
                            DateCreated = new DateTime(2024, 6, 12, 10, 35, 44, 786, DateTimeKind.Utc).AddTicks(914),
                            Name = "Отдел разработки"
                        },
                        new
                        {
                            Id = new Guid("3b12d79b-74e4-4b14-9032-5d41b08bcf90"),
                            DateCreated = new DateTime(2024, 6, 12, 10, 35, 44, 786, DateTimeKind.Utc).AddTicks(915),
                            Name = "Отдел продаж"
                        },
                        new
                        {
                            Id = new Guid("057c2651-ebec-455e-8c5b-a1b0541e4184"),
                            DateCreated = new DateTime(2024, 6, 12, 10, 35, 44, 786, DateTimeKind.Utc).AddTicks(915),
                            Name = "Отдел финансов"
                        });
                });

            modelBuilder.Entity("StaffControlServer.Data.FileSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NewsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("FileSystem");
                });

            modelBuilder.Entity("StaffControlServer.Data.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("StaffControlServer.Data.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentRoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.HasIndex("ParentRoleId");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cedeec66-2594-4a0a-a8b5-d52acfc9fb96"),
                            Name = "Системный администратор",
                            NormalizedName = "СИСТЕМНЫЙ АДМИНИСТРАТОР"
                        },
                        new
                        {
                            Id = new Guid("130c2cdb-ffce-4cf7-87c7-43e68202308b"),
                            Name = "Генеральный директор",
                            NormalizedName = "ГЕНЕРАЛЬНЫЙ ДИРЕКТОР"
                        },
                        new
                        {
                            Id = new Guid("a8454a2a-eac8-4f46-9cca-b2c60c9ce1a0"),
                            DepartmentId = new Guid("f79f1e85-ced4-4a4b-8f13-9f29bb48a90a"),
                            Name = "Руководитель отдела разработки",
                            NormalizedName = "РУКОВОДИТЕЛЬ ОТДЕЛА РАЗРАБОТКИ",
                            ParentRoleId = new Guid("130c2cdb-ffce-4cf7-87c7-43e68202308b")
                        },
                        new
                        {
                            Id = new Guid("98117452-a7de-4049-bc2a-23d6a7c7aaf7"),
                            DepartmentId = new Guid("f79f1e85-ced4-4a4b-8f13-9f29bb48a90a"),
                            Name = "Менеджер проекта",
                            NormalizedName = "МЕНЕДЖЕР ПРОЕКТА",
                            ParentRoleId = new Guid("a8454a2a-eac8-4f46-9cca-b2c60c9ce1a0")
                        },
                        new
                        {
                            Id = new Guid("a3071af5-2a91-440f-8414-1f6795ed83ce"),
                            DepartmentId = new Guid("f79f1e85-ced4-4a4b-8f13-9f29bb48a90a"),
                            Name = "Разработчик",
                            NormalizedName = "РАЗРАБОТЧИК",
                            ParentRoleId = new Guid("98117452-a7de-4049-bc2a-23d6a7c7aaf7")
                        },
                        new
                        {
                            Id = new Guid("575db12e-5808-4277-9f33-12e615b7727e"),
                            DepartmentId = new Guid("f79f1e85-ced4-4a4b-8f13-9f29bb48a90a"),
                            Name = "Тестировщик",
                            NormalizedName = "ТЕСТИРОВЩИК",
                            ParentRoleId = new Guid("98117452-a7de-4049-bc2a-23d6a7c7aaf7")
                        },
                        new
                        {
                            Id = new Guid("cdaa34de-39f8-49e1-926f-4a7b56d3fac5"),
                            DepartmentId = new Guid("a99f1722-ecf8-45bb-a049-f3c64449f304"),
                            Name = "Руководитель отдела маркеткинга",
                            NormalizedName = "РУКОВОДИТЕЛЬ ОТДЕЛА МАРКЕТКИНГА",
                            ParentRoleId = new Guid("130c2cdb-ffce-4cf7-87c7-43e68202308b")
                        },
                        new
                        {
                            Id = new Guid("492a2c48-ad06-4cb1-9591-ef631fa85252"),
                            DepartmentId = new Guid("a99f1722-ecf8-45bb-a049-f3c64449f304"),
                            Name = "Менеджер по маркетингу",
                            NormalizedName = "МЕНЕДЖЕР ПО МАРКЕТИНГУ",
                            ParentRoleId = new Guid("cdaa34de-39f8-49e1-926f-4a7b56d3fac5")
                        },
                        new
                        {
                            Id = new Guid("07dc2060-a6f6-4ebf-8ce5-1ab153550a97"),
                            DepartmentId = new Guid("a99f1722-ecf8-45bb-a049-f3c64449f304"),
                            Name = "Менеджер по продвижению",
                            NormalizedName = "МЕНЕДЖЕР ПО ПРОДВИЖЕНИЮ",
                            ParentRoleId = new Guid("cdaa34de-39f8-49e1-926f-4a7b56d3fac5")
                        },
                        new
                        {
                            Id = new Guid("cb366210-1e62-431a-bef0-5c4408d7b041"),
                            DepartmentId = new Guid("3b12d79b-74e4-4b14-9032-5d41b08bcf90"),
                            Name = "Руководитель отдела продаж",
                            NormalizedName = "РУКОВОДИТЕЛЬ ОТДЕЛА ПРОДАЖ",
                            ParentRoleId = new Guid("130c2cdb-ffce-4cf7-87c7-43e68202308b")
                        },
                        new
                        {
                            Id = new Guid("e195b50e-40b5-4d5a-b564-d61055c7f794"),
                            DepartmentId = new Guid("3b12d79b-74e4-4b14-9032-5d41b08bcf90"),
                            Name = "Менеджер по продажам",
                            NormalizedName = "МЕНЕДЖЕР ПО ПРОДАЖАМ",
                            ParentRoleId = new Guid("cb366210-1e62-431a-bef0-5c4408d7b041")
                        },
                        new
                        {
                            Id = new Guid("33a5c564-2cce-40e7-96a8-e82db77feb69"),
                            DepartmentId = new Guid("3b12d79b-74e4-4b14-9032-5d41b08bcf90"),
                            Name = "Консультант-продавец",
                            NormalizedName = "КОНСУЛЬТАНТ-ПРОДАВЕЦ",
                            ParentRoleId = new Guid("cb366210-1e62-431a-bef0-5c4408d7b041")
                        },
                        new
                        {
                            Id = new Guid("971708f1-9220-44c8-81f0-8f8c82f52564"),
                            DepartmentId = new Guid("057c2651-ebec-455e-8c5b-a1b0541e4184"),
                            Name = "Руководитель отдела финансов",
                            NormalizedName = "РУКОВОДИТЕЛЬ ОТДЕЛА ФИНАНСОВ",
                            ParentRoleId = new Guid("130c2cdb-ffce-4cf7-87c7-43e68202308b")
                        },
                        new
                        {
                            Id = new Guid("24dd6a17-b0b6-4166-88fc-def8d09bd3fa"),
                            DepartmentId = new Guid("057c2651-ebec-455e-8c5b-a1b0541e4184"),
                            Name = "Бухгалтер",
                            NormalizedName = "БУХГАЛТЕР",
                            ParentRoleId = new Guid("971708f1-9220-44c8-81f0-8f8c82f52564")
                        });
                });

            modelBuilder.Entity("StaffControlServer.Data.ToDo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ResponsibleId");

                    b.HasIndex("UserId");

                    b.ToTable("ToDoes");
                });

            modelBuilder.Entity("StaffControlServer.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TwoFactorCode")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("ParentUserId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d2351af-e8f1-4974-b776-829d47139bab"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b96860ac-b4ff-408d-a4d6-eedabf2d05f8",
                            Email = "admin@admin.admin",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.ADMIN",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEEcOm1V4yvUjBcm6VANFKIatqUSrSaDR2NiJxzJaVD8vzU62W0HPLlka6rJ+NnMUBw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a2264ee8-114d-4b2b-9886-609589bc9f8e",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("StaffControlServer.Data.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StaffControlServer.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StaffControlServer.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StaffControlServer.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("StaffControlServer.Data.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaffControlServer.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StaffControlServer.Data.ApplicationUserRole", b =>
                {
                    b.HasOne("StaffControlServer.Data.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaffControlServer.Data.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StaffControlServer.Data.Calendar", b =>
                {
                    b.HasOne("StaffControlServer.Data.User", "User")
                        .WithMany("Calendars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StaffControlServer.Data.FileSystem", b =>
                {
                    b.HasOne("StaffControlServer.Data.News", "News")
                        .WithMany("Files")
                        .HasForeignKey("NewsId");

                    b.Navigation("News");
                });

            modelBuilder.Entity("StaffControlServer.Data.News", b =>
                {
                    b.HasOne("StaffControlServer.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StaffControlServer.Data.Role", b =>
                {
                    b.HasOne("StaffControlServer.Data.Department", "Department")
                        .WithMany("Roles")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("StaffControlServer.Data.Role", "ParentRole")
                        .WithMany()
                        .HasForeignKey("ParentRoleId");

                    b.Navigation("Department");

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("StaffControlServer.Data.ToDo", b =>
                {
                    b.HasOne("StaffControlServer.Data.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaffControlServer.Data.User", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StaffControlServer.Data.User", null)
                        .WithMany("ToDoList")
                        .HasForeignKey("UserId");

                    b.Navigation("Author");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("StaffControlServer.Data.User", b =>
                {
                    b.HasOne("StaffControlServer.Data.FileSystem", "File")
                        .WithMany()
                        .HasForeignKey("FileId");

                    b.HasOne("StaffControlServer.Data.User", "ParentUser")
                        .WithMany()
                        .HasForeignKey("ParentUserId");

                    b.Navigation("File");

                    b.Navigation("ParentUser");
                });

            modelBuilder.Entity("StaffControlServer.Data.Department", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("StaffControlServer.Data.News", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("StaffControlServer.Data.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("StaffControlServer.Data.User", b =>
                {
                    b.Navigation("Calendars");

                    b.Navigation("ToDoList");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
